[package]
name = "grens"
version = "1.0.0"
description = "Grens desktop- en mobiele app"
authors = ["Philip Wintrip"]
edition = "2021"
rust-version = "1.90"

[lib]
name = "grens_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
