/* Nee-zegger Script Generator – zinnenbank / phrase bank
   Structuur per taal:
   - examples: voorbeeldverzoeken per situatie (gebruikt door "Verras me")
   - phrases:  per situatie en toon een lijst zinnen met twee varianten:
       generic = tekst als het veld leeg is
       topic   = tekst met {x} op de plek van wat de gebruiker typte
   De app kiest steeds drie willekeurige zinnen uit de passende lijst.
   Zinnen toevoegen of aanpassen kan gewoon in dit bestand. */
window.NEEZEGGER_CONTENT = {
  nl: {
    examples: {
      werk: ["een extra dienst draaien", "de vergadering van maandag", "vanavond overwerken", "een taak van een collega overnemen", "een extra project oppakken", "iets vóór het weekend opleveren"],
      sociaal: ["het etentje van vrijdag", "het feestje van zaterdag", "een belletje vanavond", "de borrel na het werk", "een weekendje weg", "bezoek dit weekend"],
      familie: ["zondag langskomen", "oppassen op de kinderen", "helpen met de verhuizing", "de verjaardag van oma", "een nachtje logeren", "het familiediner van zaterdag"],
      afspraak: ["de afspraak van dinsdag", "het gesprek van morgen", "de sessie van woensdag", "het overleg van donderdag", "de afspraak van volgende week", "de vervolgafspraak van vrijdag"],
    },
    phrases: {
      werk: {
        warm: [
          { generic: "Dank je dat je aan me denkt. Mijn antwoord is nee; ik houd mijn energie nu bij mijn eigen werk.",
            topic: "Dank je voor je bericht over {x}. Mijn antwoord is nee; ik houd mijn energie nu bij mijn eigen werk." },
          { generic: "Fijn dat je het vraagt. Dit past nu niet, en ik weet zeker dat het ook zonder mij goed komt.",
            topic: "Fijn dat je het vraagt. Wat betreft {x}: dat past nu niet, en ik weet zeker dat het ook zonder mij goed komt." },
          { generic: "Ik heb er even over nagedacht en het wordt een nee. Ik houd het nu bij wat ik al doe. Een andere keer sta ik er graag weer voor open.",
            topic: "Ik heb nagedacht over {x} en het wordt een nee. Ik houd het nu bij wat ik al doe. Een andere keer sta ik er graag weer voor open." },
          { generic: "Ik begrijp dat je het vraagt. Toch ga ik hier niet in mee; ik doe deze periode bewust rustig aan.",
            topic: "Ik begrijp dat je het vraagt. Toch zeg ik nee op {x}; ik doe deze periode bewust rustig aan." },
          { generic: "Ik waardeer het vertrouwen. Dit neem ik niet op me; ik heb mijn ruimte nu nodig voor wat er al ligt.",
            topic: "Ik waardeer het vertrouwen. Over {x}: daar kies ik nu niet voor; ik heb mijn ruimte nodig voor wat er al ligt." },
          { generic: "Ik houd mijn takenlijst voor nu zoals hij is. Dit doe ik er niet bij, en dat zeg ik liever meteen dan halverwege.",
            topic: "Je vroeg me naar {x}. Dat doe ik er niet bij, en dat zeg ik liever meteen dan halverwege." },
        ],
        kort: [
          { generic: "Nee, dit neem ik er niet bij.",
            topic: "{x}: nee, dat neem ik er niet bij." },
          { generic: "Dit past nu niet in mijn agenda.",
            topic: "Wat betreft {x}: dat past nu niet in mijn agenda." },
          { generic: "Dank je voor het vragen. Het antwoord is nee.",
            topic: "Dank je voor het vragen. Voor {x} wordt het een nee." },
          { generic: "Ik kan kort zijn: nee. Ik houd het bij wat er al ligt.",
            topic: "Ik kan kort zijn over {x}: nee. Ik houd het bij wat er al ligt." },
          { generic: "Ik zit vol. Dit komt er niet bij.",
            topic: "Ik zit vol, dus {x} komt er niet bij." },
          { generic: "Dat zit er voor mij niet in. Dank dat je het vroeg.",
            topic: "{x} zit er voor mij niet in. Dank dat je het vroeg." },
        ],
        duidelijk: [
          { generic: "Mijn antwoord is nee. Ik bewaak mijn werkdruk, en daar blijf ik bij.",
            topic: "Wat betreft {x}: mijn antwoord is nee. Ik bewaak mijn werkdruk, en daar blijf ik bij." },
          { generic: "Nee. Ik houd me aan de uren en taken die we hebben afgesproken, en dit valt daarbuiten.",
            topic: "Nee. Ik houd me aan de uren en taken die we hebben afgesproken, en {x} valt daarbuiten." },
          { generic: "Hier zeg ik nee op. Een nee is voor mij een volledig antwoord.",
            topic: "Op {x} zeg ik nee. Een nee is voor mij een volledig antwoord." },
          { generic: "Nee. Dit is mijn grens, ook als het ongelegen komt.",
            topic: "Over {x}: nee. Dit is mijn grens, ook als het ongelegen komt." },
          { generic: "Meer ruimte heb ik op dit moment niet, dus ik zeg nee. Dat mag zonder verdere onderbouwing.",
            topic: "Meer ruimte heb ik op dit moment niet, dus ik zeg nee tegen {x}. Dat mag zonder verdere onderbouwing." },
          { generic: "Voor dit verzoek geldt: nee. Ik houd mijn takenpakket zoals het nu is, en dat is een bewuste keuze.",
            topic: "Voor {x} geldt: nee. Ik houd mijn takenpakket zoals het nu is, en dat is een bewuste keuze." },
        ],
      },
      sociaal: {
        warm: [
          { generic: "Lief dat je me vraagt. Ik sla dit over; ik heb rust nodig en die gun ik mezelf.",
            topic: "Lief dat je me vraagt. Over {x}: dat sla ik over; ik heb rust nodig en die gun ik mezelf." },
          { generic: "Ik vind het fijn dat je me erbij wilt hebben. Deze keer wordt het een nee; ik kies nu voor rust. Volgende keer graag.",
            topic: "Ik vind het fijn dat je aan me denkt. {x} wordt deze keer een nee; ik kies nu voor rust. Volgende keer graag." },
          { generic: "Ik zeg nee. Niet vanwege jou, maar omdat ik een poosje niets wil. Dat heb ik nu nodig.",
            topic: "{x}: daar zeg ik nee op. Niet vanwege jou, maar omdat ik een poosje niets wil. Dat heb ik nu nodig." },
          { generic: "Dank je voor de uitnodiging. Het antwoord is nee, en ik hoop dat je weet dat dat niets over jou zegt.",
            topic: "Dank je voor je berichtje over {x}. Het antwoord is nee, en ik hoop dat je weet dat dat niets over jou zegt." },
          { generic: "Ik merk dat ik het nu rustig moet houden, dus ik pas. Fijn dat je het me vroeg, dat betekent veel.",
            topic: "Ik merk dat ik het nu rustig moet houden, dus {x} zit er voor mij niet in. Fijn dat je het me vroeg, dat betekent veel." },
          { generic: "Ik ben wat stiller dan anders en dat is oké. Nu niet, maar ik ben je niet vergeten. Ik app je als ik weer ruimte heb.",
            topic: "Ik ben wat stiller dan anders en dat is oké. Voor {x} zeg ik nee, maar ik ben je niet vergeten. Ik app je als ik weer ruimte heb." },
        ],
        kort: [
          { generic: "Nee, nu niet. Rust gaat voor.",
            topic: "Over {x}: nee, rust gaat nu voor." },
          { generic: "Nee, deze keer niet. Lief dat je vroeg.",
            topic: "{x}: nee. Lief dat je vroeg." },
          { generic: "Ik heb rust nodig, dus ik pas deze keer.",
            topic: "Ik heb rust nodig, dus ik pas voor {x}." },
          { generic: "Nee, maar ik denk wel aan je.",
            topic: "{x}? Nee, maar ik denk wel aan je." },
          { generic: "Ik sla dit over. Fijn dat je aan me dacht.",
            topic: "{x} sla ik deze keer over. Fijn dat je aan me dacht." },
          { generic: "Nu niet. Zodra ik weer ruimte heb, hoor je van me.",
            topic: "Voor {x} is het nu nee. Zodra ik weer ruimte heb, hoor je van me." },
        ],
        duidelijk: [
          { generic: "Dit wordt een nee. Het is een keuze voor rust, geen oordeel over jou.",
            topic: "{x}: dat wordt een nee. Het is een keuze voor rust, geen oordeel over jou." },
          { generic: "Nee, ik doe niet mee. Ik hoef daar geen reden bij te geven; het is gewoon wat ik nu nodig heb.",
            topic: "Over {x}: nee. Ik hoef daar geen reden bij te geven; het is gewoon wat ik nu nodig heb." },
          { generic: "Ik houd mijn agenda voorlopig leeg, en dit valt daar ook onder. Meer zit er niet achter.",
            topic: "Ik houd mijn agenda voorlopig leeg, en {x} valt daar ook onder. Meer zit er niet achter." },
          { generic: "Ik heb dit goed overwogen en ik zeg nee. Dat voelt als de juiste keuze.",
            topic: "{x} heb ik goed overwogen en ik zeg nee. Dat voelt als de juiste keuze." },
          { generic: "Mijn antwoord is nee, en dat staat vast. Ik weet wat ik nu nodig heb.",
            topic: "Je vraag over {x}: mijn antwoord is nee, en dat staat vast. Ik weet wat ik nu nodig heb." },
          { generic: "Ik zeg het zonder omhaal, zodat je niet op me hoeft te rekenen: het is een nee.",
            topic: "Ik zeg het zonder omhaal, zodat je niet op me hoeft te rekenen: {x} is een nee." },
        ],
      },
      familie: {
        warm: [
          { generic: "Nee, ik heb rust nodig en die neem ik nu. Ik hou van jullie, en dit verandert daar niets aan.",
            topic: "Over {x}: nee, ik heb rust nodig en die neem ik nu. Ik hou van jullie, en dit verandert daar niets aan." },
          { generic: "Lief dat je het vraagt. Ik zeg deze keer nee. Vraag me gerust een andere keer weer.",
            topic: "Lief dat je het vraagt. Ik heb nagedacht over {x} en ik zeg nee. Vraag me gerust een andere keer weer." },
          { generic: "Fijn dat je aan me dacht, en toch sla ik het deze keer over. Dat zegt niets over hoe belangrijk je voor me bent.",
            topic: "{x}: dat sla ik deze keer over. Dat zegt niets over hoe belangrijk je voor me bent." },
          { generic: "Ik hou van je, en toch is dit voor mij nu een nee. Mijn energie is beperkt en ik kies ervoor die goed te bewaren.",
            topic: "Ik hou van je, en toch is {x} voor mij nu een nee. Mijn energie is beperkt en ik kies ervoor die goed te bewaren." },
          { generic: "Wat lief dat je aan me denkt. Dat past nu niet, dus het wordt een nee. Ik laat het je weten als ik weer ruimte heb.",
            topic: "Dank je voor je berichtje over {x}. Dat past nu niet, dus het wordt een nee. Ik laat het je weten als ik weer ruimte heb." },
          { generic: "Deze keer niet, en dat mag ik gewoon zeggen. Je hoeft je geen zorgen te maken. Dikke knuffel.",
            topic: "Je vraag over {x}: deze keer niet, en dat mag ik gewoon zeggen. Je hoeft je geen zorgen te maken. Dikke knuffel." },
        ],
        kort: [
          { generic: "Niet dit keer. Ik heb rust nodig.",
            topic: "{x}: niet dit keer. Ik heb rust nodig." },
          { generic: "Nee, en ik zeg het met liefde.",
            topic: "{x}? Nee, en ik zeg het met liefde." },
          { generic: "Nu niet. Ik laat snel van me horen. Liefs.",
            topic: "{x}: nu niet. Ik laat snel van me horen. Liefs." },
          { generic: "Nee, ik houd het thuis rustig, ook dit keer.",
            topic: "Nee, ik houd het thuis rustig, ook als het om {x} gaat." },
          { generic: "Lief van je om het te vragen. Daar zeg ik nee op, met een dikke knuffel.",
            topic: "Lief van je om het te vragen. {x}: nee, met een dikke knuffel." },
          { generic: "Dit zit er nu niet in, maar ik ben er wel voor je.",
            topic: "{x} zit er nu niet in, maar ik ben er wel voor je." },
        ],
        duidelijk: [
          { generic: "Nee. Dat antwoord is compleet zoals het is; ik hoef er geen uitleg bij te geven.",
            topic: "{x}: nee. Dat antwoord is compleet zoals het is; ik hoef er geen uitleg bij te geven." },
          { generic: "Ik hou van jullie én ik zeg nee. Die twee kunnen naast elkaar bestaan.",
            topic: "Ik hou van jullie én ik zeg nee tegen {x}; die twee kunnen naast elkaar bestaan." },
          { generic: "Dit sla ik over. Ik bewaak mijn energie en dat is mijn verantwoordelijkheid, niet die van jou.",
            topic: "{x} sla ik over. Ik bewaak mijn energie en dat is mijn verantwoordelijkheid, niet die van jou." },
          { generic: "Het is nee. Dat is geen afwijzing van jou.",
            topic: "Voor {x} is mijn antwoord nee; dat is geen afwijzing van jou." },
          { generic: "Ik houd het voorlopig rustig, dus daar zeg ik nee op. Dat is geen afstand nemen; ik heb het gewoon nodig.",
            topic: "Ik houd het voorlopig rustig, dus op {x} zeg ik nee. Dat is geen afstand nemen; ik heb het gewoon nodig." },
          { generic: "Deze keer kies ik voor mezelf, en dat mag. Het antwoord is dus nee.",
            topic: "Deze keer kies ik voor mezelf, en dat mag. Voor {x} betekent dat: nee." },
        ],
      },
      afspraak: {
        warm: [
          { generic: "Ik verzet onze afspraak. Ik heb nu rust nodig, en ik stuur je snel een paar nieuwe opties.",
            topic: "Over {x}: dat wordt een later moment. Ik heb nu rust nodig en stuur je snel een paar nieuwe opties." },
          { generic: "Dank je voor je bericht. Onze afspraak zeg ik voor nu af; ik neem zelf contact op voor een nieuw moment.",
            topic: "Dank je voor je bericht over {x}. Ik zeg het voor nu af; ik neem zelf contact op voor een nieuw moment." },
          { generic: "Onze afspraak schuif ik liever naar een later moment. Deze periode houd ik voor mezelf; zodra ik er weer ruimte voor heb, hoor je van mij.",
            topic: "{x} schuif ik liever naar een later moment. Deze periode houd ik voor mezelf; zodra ik er weer ruimte voor heb, hoor je van mij." },
          { generic: "Ik heb erover nagedacht en ik plan het liever later opnieuw. Ik houd het nu rustig. Ik kom er zelf op terug.",
            topic: "Ik heb nagedacht over {x}. Dat plan ik liever later opnieuw; ik houd het nu rustig. Ik kom er zelf op terug." },
          { generic: "Ik merk dat ik meer ruimte nodig heb dan ik dacht, dus ik zeg onze afspraak af. Ik laat je weten wanneer het wel kan.",
            topic: "Ik merk dat ik meer ruimte nodig heb dan ik dacht, dus {x} wordt een andere keer. Ik laat je weten wanneer het wel kan." },
          { generic: "Ik zeg het liever eerlijk: onze afspraak gaat voor mij nu niet door. Ik plan zelf een nieuw moment als ik daar ruimte voor heb.",
            topic: "Ik zeg het liever eerlijk: {x} gaat voor mij nu niet door. Ik plan zelf een nieuw moment als ik daar ruimte voor heb." },
        ],
        kort: [
          { generic: "Onze afspraak verzet ik. Ik stuur je nieuwe opties.",
            topic: "{x}: nu niet. Ik stuur je nieuwe opties." },
          { generic: "Ik zeg af. Ik neem zelf weer contact op.",
            topic: "Wat betreft {x}: ik zeg af en neem zelf weer contact op." },
          { generic: "Dit moment lukt niet. Ik stuur je een nieuw voorstel.",
            topic: "Over {x}: dat lukt nu niet. Ik stuur je een nieuw voorstel." },
          { generic: "Dat wordt later. Je hoort van mij wanneer.",
            topic: "{x}: dat wordt later. Je hoort van mij wanneer." },
          { generic: "Ik kies een later moment. Ik geef zelf door wanneer.",
            topic: "Voor {x} kies ik een later moment. Ik geef zelf door wanneer." },
          { generic: "Onze afspraak schuif ik door. Ik stel zelf een nieuw moment voor.",
            topic: "Ik schuif {x} door en stel zelf een nieuw moment voor." },
        ],
        duidelijk: [
          { generic: "Onze afspraak gaat niet door. Ik hoef daar geen reden voor te geven; ik laat weten wanneer ik weer kan.",
            topic: "{x} gaat voor mij niet door. Ik hoef daar geen reden voor te geven; ik laat weten wanneer ik weer kan." },
          { generic: "Ik verplaats onze afspraak naar een later moment. Ik kom zelf met een nieuw voorstel.",
            topic: "Wat betreft {x}: dat verplaats ik naar een later moment. Ik kom zelf met een nieuw voorstel." },
          { generic: "Ik zeg onze afspraak af. Ik plan het zelf later opnieuw in; daar hoef jij niets voor te doen.",
            topic: "{x} zeg ik af. Ik plan het zelf later opnieuw in; daar hoef jij niets voor te doen." },
          { generic: "Nee, dit moment past niet. Een nieuwe datum komt van mijn kant.",
            topic: "Nee, {x} past nu niet. Een nieuwe datum komt van mijn kant." },
          { generic: "Onze afspraak zet ik voorlopig stil. Ik plan zelf later een moment.",
            topic: "{x} zet ik voorlopig stil. Ik plan zelf later een moment." },
          { generic: "Ik plan de komende tijd niets in, dus ook onze afspraak niet. Dat is een keuze, geen aarzeling.",
            topic: "Ik plan de komende tijd niets in, dus ook {x} niet. Dat is een keuze, geen aarzeling." },
        ],
      },
    },
  },
  en: {
    examples: {
      werk: ["taking an extra shift", "covering for a colleague", "working late on Friday", "joining another meeting", "delivering something before the weekend", "taking on an extra project"],
      sociaal: ["Friday's dinner", "a party on Saturday", "a quick call tonight", "a visit this weekend", "a weekend away", "drinks after work"],
      familie: ["coming over on Sunday", "helping with the move", "a family birthday", "babysitting the kids", "the kids sleeping over", "a family visit on Saturday"],
      afspraak: ["Tuesday's appointment", "tomorrow's meeting", "Thursday's call", "next week's session", "Friday's check-in", "the follow-up on Monday"],
    },
    phrases: {
      werk: {
        warm: [
          { generic: "Thanks for thinking of me. I'm going to sit this one out; my energy is going into my own workload right now.",
            topic: "Thanks for asking about {x}. I'm going to sit this one out; my energy is going into my own workload right now." },
          { generic: "Good of you to ask. This isn't something I can take on right now, and I'm sure it'll work out without me.",
            topic: "Good of you to ask. As for {x}, it isn't something I can take on right now, and I'm sure it'll work out without me." },
          { generic: "I've given it some thought and the answer is no. My energy is limited at the moment. Another time, I'd be glad to.",
            topic: "I've thought about {x} and the answer is no. My energy is limited at the moment. Another time, I'd be glad to." },
          { generic: "I know things are busy. Even so, I'm going to decline; I'm keeping my calendar deliberately light for now.",
            topic: "I know things are busy. Even so, my answer on {x} is no; I'm keeping my calendar deliberately light for now." },
          { generic: "I appreciate you asking. It's still a no; the space I have is needed for what's already on my plate.",
            topic: "I appreciate you asking. It's still a no to {x}; the space I have is needed for what's already on my plate." },
          { generic: "I'm keeping my workload as it is for now. I'm not adding this, and I'd rather say so straight away.",
            topic: "I'm keeping my workload as it is for now. You asked about {x}, and I'm not adding it; I'd rather say so straight away." },
        ],
        kort: [
          { generic: "I'm going to have to say no to this.",
            topic: "I'm going to have to say no to {x}." },
          { generic: "That's not going to work for me right now.",
            topic: "As for {x}, that's not going to work for me right now." },
          { generic: "This one is a no from me.",
            topic: "On {x}, it's a no from me." },
          { generic: "It's a no; I'm sticking with what I've already got on.",
            topic: "It's a no to {x}; I'm sticking with what I've already got on." },
          { generic: "Thanks for asking. The answer is no.",
            topic: "Regarding {x}: thanks for asking, and the answer is no." },
          { generic: "I'm at capacity, so this doesn't fit.",
            topic: "I'm at capacity, so {x} doesn't fit." },
        ],
        duidelijk: [
          { generic: "My answer to this is no. That's the whole message, and I'm comfortable leaving it there.",
            topic: "My answer to your question about {x} is no. That's the whole message, and I'm comfortable leaving it there." },
          { generic: "This is a no. I'm protecting my workload, and I'm firm on that.",
            topic: "As for {x}: it's a no. I'm protecting my workload, and I'm firm on that." },
          { generic: "This falls outside what I've agreed to take on, and I'm keeping to that.",
            topic: "What I've agreed to take on doesn't include {x}, and I'm keeping to that." },
          { generic: "I'm turning this down. A no is enough on its own; it doesn't need backing up.",
            topic: "That's a no from me on {x}. A no is enough on its own; it doesn't need backing up." },
          { generic: "No. I'm holding the line on this, even if the timing is inconvenient.",
            topic: "About {x}: no. I'm holding the line on this, even if the timing is inconvenient." },
          { generic: "I'm saying no, and that's settled. I'm keeping my hours where they are.",
            topic: "Regarding {x}: I'm saying no, and that's settled. I'm keeping my hours where they are." },
        ],
      },
      sociaal: {
        warm: [
          { generic: "Lovely of you to ask. I'm going to give this one a miss; I need some rest and I'm letting myself have it.",
            topic: "Lovely of you to ask. About {x}: I'm going to give it a miss; I need some rest and I'm letting myself have it." },
          { generic: "I'd love to say yes, but this time I'm choosing rest, so it's a no. Next time, definitely.",
            topic: "I'd love to say yes, but this time I'm choosing rest, so it's a no to {x}. Next time, definitely." },
          { generic: "It's a no from me this time. Not because I don't want to see you, but because I want nothing on for a while. Let's catch up when I've got more energy.",
            topic: "This time {x} is a no from me. Not because I don't want to see you, but because I want nothing on for a while. Let's catch up when I've got more energy." },
          { generic: "Thanks for the invite. I'm going to pass on this one, and I hope you know that says nothing about you.",
            topic: "Thanks for your message about {x}. I'm going to pass on this one, and I hope you know that says nothing about you." },
          { generic: "I can tell I need a quiet stretch right now, so I won't be joining. Thank you for asking; it means a lot.",
            topic: "I can tell I need a quiet stretch right now, and that means saying no to {x}. Thank you for asking; it means a lot." },
          { generic: "I'm a bit quieter than usual at the moment, and that's okay. Not this time, but I haven't forgotten you; I'll be in touch when I've got space again.",
            topic: "I'm a bit quieter than usual at the moment, and that's okay. You asked about {x}: not this time, but I haven't forgotten you. I'll be in touch when I've got space again." },
        ],
        kort: [
          { generic: "I'm going to skip this one. Rest comes first.",
            topic: "I'm going to skip {x}. Rest comes first." },
          { generic: "I'm going to bow out of this one. Kind of you to ask.",
            topic: "Kind of you to ask about {x}, but I'm bowing out this time." },
          { generic: "My energy is limited, so this one's a no.",
            topic: "My energy is limited, so it's a no to {x}." },
          { generic: "It's a no for now, but you're on my mind.",
            topic: "For now {x} is a no, but you're on my mind." },
          { generic: "Thanks for asking. I'm going to pass on this one.",
            topic: "Thanks for asking. I'm going to pass on {x}." },
          { generic: "I'll be straight: it's a no right now. I'll give you a shout when I'm up for things again.",
            topic: "I'll be straight about {x}: it's a no right now. I'll give you a shout when I'm up for things again." },
        ],
        duidelijk: [
          { generic: "This no is about rest, not about you.",
            topic: "I'm saying no to {x}. That's about rest, not about you." },
          { generic: "No. I'm leaving it at that, without a reason attached.",
            topic: "The answer to {x} is no. I'm leaving it at that, without a reason attached." },
          { generic: "I'm keeping my calendar clear for now, and this isn't going on it. I'm certain about that.",
            topic: "I'm keeping my calendar clear for now, and {x} isn't going on it. I'm certain about that." },
          { generic: "I've thought this through properly and my answer is no. No need to wait on me.",
            topic: "I've thought properly about {x} and my answer is no. No need to wait on me." },
          { generic: "It's a no, and I'm settled on that; I know what I need right now.",
            topic: "On {x}: it's a no, and I'm settled on that; I know what I need right now." },
          { generic: "Count me out this time. I'm saying it plainly so there's no maybe hanging in the air.",
            topic: "Count me out for {x}. I'm saying it plainly so there's no maybe hanging in the air." },
        ],
      },
      familie: {
        warm: [
          { generic: "This time it's a no; I'm giving myself a breather. I love you all, and that doesn't change a thing.",
            topic: "I'm going to say no to {x}; I'm giving myself a breather. I love you all, and that doesn't change a thing." },
          { generic: "Sweet of you to ask. It's a no for now. Another time, when things are calmer, I'd love to.",
            topic: "Sweet of you to ask about {x}. It's a no for now. Another time, when things are calmer, I'd love to." },
          { generic: "Glad you thought of me. This time I'm going to pass. That says nothing about how much you mean to me.",
            topic: "Glad you thought of me. This time I'm going to pass on {x}. That says nothing about how much you mean to me." },
          { generic: "Nothing but love here, and it's still a no from me. My energy is limited and I'm choosing to look after it.",
            topic: "Nothing but love here, and {x} is still a no from me. My energy is limited and I'm choosing to look after it." },
          { generic: "Thank you for asking. It's a no at the moment, and I'll let you know when I have room again.",
            topic: "Thank you for asking about {x}. It's a no at the moment, and I'll let you know when I have room again." },
          { generic: "It's a no this time. Nothing's wrong; I just need the space. Big hug.",
            topic: "About {x}: it's a no. Nothing's wrong; I just need the space. Big hug." },
        ],
        kort: [
          { generic: "Not this time; I'm taking it easy for a bit.",
            topic: "This time {x} gets a no; I'm taking it easy for a bit." },
          { generic: "Love you, and it's a no. I'll be in touch soon.",
            topic: "Love you, and it's a no to {x}. I'll be in touch soon." },
          { generic: "No, and I say it with love.",
            topic: "No to {x}, and I say it with love." },
          { generic: "I'm not taking anything on for now, and this is no exception.",
            topic: "I'm not taking anything on for now, and {x} is no exception." },
          { generic: "Thanks for thinking of me, but I'm not up for it. I'm keeping my time free.",
            topic: "Thanks for thinking of me, but I'm not up for {x}. I'm keeping my time free." },
          { generic: "I'm going to say no, but I'm always glad to hear from you.",
            topic: "I'm passing on {x}, but I'm always glad to hear from you." },
        ],
        duidelijk: [
          { generic: "To be clear: the answer is no, and it doesn't need explaining. That's all there is to it.",
            topic: "To be clear about {x}: the answer is no, and it doesn't need explaining. That's all there is to it." },
          { generic: "I love you, and this is a no. Both of those can be true at once.",
            topic: "I love you, and {x} is a no. Both of those can be true at once." },
          { generic: "It's a firm no. Protecting my energy is my responsibility, and I take it seriously.",
            topic: "It's a firm no to {x}. Protecting my energy is my responsibility, and I take it seriously." },
          { generic: "This gets a no from me, and that isn't a rejection of you. It's simply where I am right now.",
            topic: "It's a no from me on {x}, and that isn't a rejection of you. It's simply where I am right now." },
          { generic: "This is a no: my energy is limited and I'm spending it carefully. That's not me pulling away; it's me being honest about what I can give.",
            topic: "When it comes to {x}, it's a no: my energy is limited and I'm spending it carefully. That's not me pulling away; it's me being honest about what I can give." },
          { generic: "I'm putting myself first this time, and that means a no. That's a full answer.",
            topic: "I'm putting myself first this time, and that means a no to {x}. That's a full answer." },
        ],
      },
      afspraak: {
        warm: [
          { generic: "Our appointment isn't going to happen as it stands; I need to take things slower right now. Sorry to move things around; I'll send you a few new times soon.",
            topic: "As for {x}, that isn't going to happen as it stands; I need to take things slower right now. Sorry to move things around; I'll send you a few new times soon." },
          { generic: "A quick update on our appointment: I'm cancelling it for now; I'll get in touch when I'm ready to find a new time.",
            topic: "A quick update on {x}: I'm cancelling it for now; I'll get in touch when I'm ready to find a new time." },
          { generic: "I'd like to push our appointment back to a later date; I'm keeping some space for myself for now. Let me know what suits you.",
            topic: "I'd like to push {x} back to a later date; I'm keeping some space for myself for now. Let me know what suits you." },
          { generic: "I'd rather reschedule our appointment for later; I'm short on energy right now. I'll come back to you when the time is right.",
            topic: "I'd rather reschedule {x} for later; I'm short on energy right now. I'll come back to you when the time is right." },
          { generic: "I'm finding I need more space than I expected, so our appointment is going on hold. I'll let you know when I'm ready to pick a new date.",
            topic: "I'm finding I need more space than I expected, so {x} is going on hold. I'll let you know when I'm ready to pick a new date." },
          { generic: "I'm going to keep our appointment short this time, and I'd appreciate you bearing with me on that.",
            topic: "I'm going to keep {x} short this time, and I'd appreciate you bearing with me on that." },
        ],
        kort: [
          { generic: "I need to reschedule our appointment. New times to follow.",
            topic: "I need to reschedule {x}. New times to follow." },
          { generic: "I'm cancelling our appointment. That's all from me for now.",
            topic: "I'm cancelling {x}. That's all from me for now." },
          { generic: "That time doesn't work for me. I'll suggest something else.",
            topic: "Right now {x} doesn't work for me. I'll suggest something else." },
          { generic: "I'm keeping our appointment short this time.",
            topic: "About {x}: I'm keeping it short this time." },
          { generic: "I'd like to postpone our appointment. I'll come back to you with a new date.",
            topic: "I'd like to postpone {x}. I'll come back to you with a new date." },
          { generic: "Our appointment isn't going ahead right now. I'll rebook when I'm ready.",
            topic: "For now {x} isn't going ahead. I'll rebook when I'm ready." },
        ],
        duidelijk: [
          { generic: "Our appointment is cancelled, and that doesn't need a reason. I'll let you know when I'm available again.",
            topic: "Regarding {x}: I'm cancelling it, and that doesn't need a reason. I'll let you know when I'm available again." },
          { generic: "I'm moving our appointment to a later date. That's decided; I'll send you a new time.",
            topic: "I'm moving {x} to a later date. That's decided; I'll send you a new time." },
          { generic: "I'm not going ahead with our appointment, and I'm not rebooking for now. I'll be in touch if that changes.",
            topic: "About {x}: I'm not going ahead with it, and I'm not rebooking for now. I'll be in touch if that changes." },
          { generic: "I'm keeping our appointment short. That's the limit I'm setting right now.",
            topic: "When it comes to {x}, I'm keeping it short. That's the limit I'm setting right now." },
          { generic: "I'm not going to fit this in right now, and that's firm. I'll find a new time when I have space.",
            topic: "I'm not going to fit {x} in right now, and that's firm. I'll find a new time when I have space." },
          { generic: "I've cleared my calendar for a while, and that includes our appointment, so it's off. I'll get back to you once things open up again.",
            topic: "I've cleared my calendar for a while, and that includes {x}, so it's off. I'll get back to you once things open up again." },
        ],
      },
    },
  },
};
