/* Nee-zegger Script Generator – zinnenbank / phrase bank
   Structuur per taal:
   - examples: voorbeeldverzoeken per situatie (gebruikt door "Verras me")
   - phrases:  per situatie en toon een lijst zinnen met twee varianten:
       generic = tekst als het veld leeg is
       topic   = tekst met {x} op de plek van wat de gebruiker typte
   De app kiest steeds drie willekeurige zinnen uit de passende lijst.
   Zinnen toevoegen of aanpassen kan gewoon in dit bestand. */
window.NEEZEGGER_CONTENT = {
  nl: {
    examples: {
      werk: ["een extra dienst draaien", "een taak van een collega overnemen", "vanavond overwerken", "een vergadering erbij", "iets vóór het weekend opleveren", "een extra project oppakken"],
      sociaal: ["een etentje afzeggen", "het feestje van zaterdag", "even bellen vanavond", "bezoek dit weekend", "een weekendje weg", "de borrel na het werk"],
      familie: ["zondag niet langskomen", "meehelpen met de verhuizing", "de verjaardag van oma", "oppassen op de kinderen", "een nachtje logeren", "familiebezoek op zaterdag"],
      afspraak: ["een afspraak verzetten", "de afspraak van dinsdag afzeggen", "later opnieuw plannen", "de afspraak korter maken", "verplaatsen naar volgende week", "het gesprek van morgen uitstellen"],
    },
    phrases: {
      werk: {
        warm: [
          { generic: "Dank je dat je aan me denkt. Ik ga deze extra dienst niet draaien; ik houd mijn energie nu bij mijn eigen werk.",
            topic: "Dank je voor je bericht over {x}. Ik doe het deze keer niet; ik houd mijn energie nu bij mijn eigen werk." },
          { generic: "Fijn dat je het vraagt. Dit past nu niet bij mij, en ik weet zeker dat het ook zonder mij goed komt.",
            topic: "Fijn dat je het vraagt. Even over {x}: dat past nu niet bij mij, en ik weet zeker dat het ook zonder mij goed komt." },
          { generic: "Ik heb er even over nagedacht en ik zeg nee. Mijn energie is op dit moment beperkt. Een andere keer denk ik graag weer mee.",
            topic: "Ik heb nagedacht over {x} en ik zeg nee. Mijn energie is op dit moment beperkt. Een andere keer denk ik graag weer mee." },
          { generic: "Ik snap dat het druk is. Toch ga ik hier niet in mee; ik houd mijn agenda deze periode bewust rustig.",
            topic: "Ik snap dat het druk is. Over {x}: daar ga ik niet in mee; ik houd mijn agenda deze periode bewust rustig." },
          { generic: "Ik waardeer het vertrouwen. Dit neem ik niet op me; ik heb mijn ruimte nu nodig voor wat er al ligt.",
            topic: "Wat betreft {x}: ik waardeer het vertrouwen, en toch neem ik het niet op me. Ik heb mijn ruimte nu nodig voor wat er al ligt." },
          { generic: "Ik houd mijn takenlijst voor nu zoals hij is. Dit komt er niet bij, en dat zeg ik liever meteen dan halverwege.",
            topic: "Ik houd mijn takenlijst voor nu zoals hij is. Je vroeg me over {x}; dat komt er niet bij, en dat zeg ik liever meteen dan halverwege." },
        ],
        kort: [
          { generic: "Ik draai deze extra dienst niet.",
            topic: "Over {x}: nee, dat doe ik niet." },
          { generic: "Dit past nu niet in mijn agenda.",
            topic: "Wat betreft {x}: dat past nu niet in mijn agenda." },
          { generic: "Nee, dit pak ik niet op. Dank voor het vragen.",
            topic: "Even over {x}: dat pak ik niet op. Dank voor het vragen." },
          { generic: "Ik houd het bij wat er al ligt.",
            topic: "Ik heb nagedacht over {x}. Ik houd het bij wat er al ligt." },
          { generic: "Dank je voor het vragen. Het antwoord is nee.",
            topic: "Dank je voor je vraag over {x}. Het antwoord is nee." },
          { generic: "Ik zit vol. Dit komt er niet bij.",
            topic: "Ik zit vol, dus over {x} zeg ik nee." },
        ],
        duidelijk: [
          { generic: "Ik draai deze extra dienst niet. Dat is mijn antwoord, en een uitleg hoort daar niet bij.",
            topic: "Wat betreft {x}: dat doe ik niet. Dat is mijn antwoord, en een uitleg hoort daar niet bij." },
          { generic: "Mijn antwoord is nee, en dat blijft zo als je het later nog eens vraagt. Ik bewaak mijn werkdruk.",
            topic: "Over {x} is mijn antwoord nee, en dat blijft zo als je het later nog eens vraagt. Ik bewaak mijn werkdruk." },
          { generic: "Dit neem ik niet op me. Ik houd me aan de uren en taken die we hebben afgesproken.",
            topic: "Je vroeg me over {x}. Dat neem ik niet op me; ik houd me aan de uren en taken die we hebben afgesproken." },
          { generic: "Ik ga hier niet in mee. Je hoeft er geen goede reden van me bij te verwachten; een nee is genoeg.",
            topic: "Ik heb nagedacht over {x} en ik ga er niet in mee. Je hoeft er geen goede reden van me bij te verwachten; een nee is genoeg." },
          { generic: "Nee. Ik bewaak mijn grens hierin, ook als het ongelegen komt.",
            topic: "Even over {x}: nee. Ik bewaak mijn grens hierin, ook als het ongelegen komt." },
          { generic: "Ik zeg nee, en dat mag zonder verdere onderbouwing. Mijn beschikbaarheid is op dit moment wat ze is.",
            topic: "Dank je voor je bericht over {x}. Ik zeg nee, en dat mag zonder verdere onderbouwing. Mijn beschikbaarheid is op dit moment wat ze is." },
        ],
      },
      sociaal: {
        warm: [
          { generic: "Lief dat je me vraagt. Ik sla dit etentje over; ik heb even rust nodig en dat gun ik mezelf.",
            topic: "Lief dat je me vraagt. Even over {x}: dat sla ik over; ik heb even rust nodig en dat gun ik mezelf." },
          { generic: "Ik vind het fijn dat je me erbij wilt hebben. Deze keer kom ik niet; ik kies voor een rustige avond. Volgende keer graag.",
            topic: "Ik vind het fijn dat je aan me denkt. Ik heb nagedacht over {x} en ik kies deze keer voor rust. Volgende keer graag." },
          { generic: "Ik zeg nee. Niet omdat ik jou niet wil zien, maar omdat ik even niets wil. Snel weer iets samen?",
            topic: "Over {x}: nee. Niet omdat ik jou niet wil zien, maar omdat ik even niets wil. Snel weer iets samen?" },
          { generic: "Dank je voor de uitnodiging. Deze keer niet, en ik hoop dat je weet dat dat niets over jou zegt.",
            topic: "Dank je voor je bericht over {x}. Deze keer niet, en ik hoop dat je weet dat dat niets over jou zegt." },
          { generic: "Ik merk dat ik het nu rustig moet houden, dus ik kom niet. Fijn dat je het me vroeg, dat betekent veel.",
            topic: "Ik merk dat ik het nu rustig moet houden. Wat betreft {x}: ik pas. Fijn dat je het me vroeg, dat betekent veel." },
          { generic: "Ik ben even wat stiller dan anders en dat is oké. Deze keer kom ik niet, maar ik ben je niet vergeten. Ik app je als ik weer ruimte heb.",
            topic: "Ik ben even wat stiller dan anders en dat is oké. Je vroeg me over {x}: deze keer niet, maar ik ben je niet vergeten. Ik app je als ik weer ruimte heb." },
        ],
        kort: [
          { generic: "Ik zeg het etentje af. Rust gaat nu voor.",
            topic: "Over {x}: nee, rust gaat nu voor." },
          { generic: "Ik sla deze over. Lief dat je vroeg.",
            topic: "Even over {x}: ik sla het over. Lief dat je vroeg." },
          { generic: "Deze keer niet. Ik heb rust nodig.",
            topic: "Wat betreft {x}: deze keer niet. Ik heb rust nodig." },
          { generic: "Ik kom niet, maar ik denk aan je.",
            topic: "Ik heb nagedacht over {x}: nu niet, maar ik denk aan je." },
          { generic: "Dank je voor het vragen. Ik pas even.",
            topic: "Dank je voor je berichtje over {x}. Ik pas even." },
          { generic: "Nu even niet. Ik app je zelf als ik weer ruimte heb.",
            topic: "Je vroeg me over {x}. Nu even niet; ik app je zelf als ik weer ruimte heb." },
        ],
        duidelijk: [
          { generic: "Ik kom niet naar het etentje. Dat is een keuze voor rust, geen oordeel over jou.",
            topic: "Over {x}: mijn antwoord is nee. Dat is een keuze voor rust, geen oordeel over jou." },
          { generic: "Nee, ik ben er niet bij. Ik hoef daar geen reden bij te geven en jij hoeft er niets mee te doen.",
            topic: "Wat betreft {x}: nee. Ik hoef daar geen reden bij te geven en jij hoeft er niets mee te doen." },
          { generic: "Ik houd mijn agenda voorlopig leeg, en dit valt daar ook onder. Dat verandert niet als je het nog eens vraagt.",
            topic: "Ik houd mijn agenda voorlopig leeg, en {x} valt daar ook onder. Dat verandert niet als je het nog eens vraagt." },
          { generic: "Ik heb hier goed over nagedacht en mijn antwoord is nee. Meer uitleg heb ik er niet bij.",
            topic: "Ik heb goed nagedacht over {x} en mijn antwoord is nee. Meer uitleg heb ik er niet bij." },
          { generic: "Mijn antwoord is nee, en ik ga er niet over onderhandelen. Ik weet wat ik nu nodig heb.",
            topic: "Je vroeg me over {x}. Mijn antwoord is nee, en ik ga er niet over onderhandelen. Ik weet wat ik nu nodig heb." },
          { generic: "Ik doe niet mee, ook niet eventjes. Ik zeg het zonder omhaal, zodat je niet op me hoeft te rekenen.",
            topic: "Even over {x}: ik doe niet mee, ook niet eventjes. Ik zeg het zonder omhaal, zodat je niet op me hoeft te rekenen." },
        ],
      },
      familie: {
        warm: [
          { generic: "Ik kom zondag niet langs. Ik heb een rustig weekend nodig. Ik hou van jullie, dat verandert hier niets aan.",
            topic: "Over {x}: ik heb rust nodig en die neem ik nu. Ik hou van jullie, dat verandert hier niets aan." },
          { generic: "Lief dat je het vraagt. Ik doe het deze keer niet. Ik kom graag een andere keer, op een rustig moment.",
            topic: "Lief dat je het vraagt. Ik heb nagedacht over {x} en ik zeg nee. Ik kom graag een andere keer, op een rustig moment." },
          { generic: "Fijn dat je aan me dacht. Deze keer doe ik niet mee. Dat zegt niets over hoe belangrijk jullie voor me zijn.",
            topic: "Fijn dat je aan me dacht. Wat betreft {x}: deze keer doe ik niet mee. Dat zegt niets over hoe belangrijk jullie voor me zijn." },
          { generic: "Ik hou van jullie, en ik zeg nu toch nee. Mijn energie is beperkt en ik kies ervoor die goed te bewaren.",
            topic: "Ik hou van jullie, en over {x} zeg ik nu toch nee. Mijn energie is beperkt en ik kies ervoor die goed te bewaren." },
          { generic: "Dank je dat je aan me denkt. Dit past nu niet bij mij. Ik laat het je weten als ik weer ruimte heb.",
            topic: "Dank je voor je bericht over {x}. Dit past nu niet bij mij. Ik laat het je weten als ik weer ruimte heb." },
          { generic: "Deze keer kom ik niet, en dat mag ik gewoon zeggen zonder dat er iets aan de hand is. Knuffel voor iedereen.",
            topic: "Even over {x}: deze keer niet, en dat mag ik gewoon zeggen zonder dat er iets aan de hand is. Knuffel voor iedereen." },
        ],
        kort: [
          { generic: "Ik kom zondag niet. Ik heb rust nodig.",
            topic: "Over {x}: ik heb rust nodig, en die neem ik." },
          { generic: "Deze keer niet. Liefs, ik bel je snel.",
            topic: "Wat betreft {x}: deze keer niet. Liefs, ik bel je snel." },
          { generic: "Nee, en ik zeg het met liefde.",
            topic: "Even over {x}: nee, en ik zeg het met liefde." },
          { generic: "Ik houd mijn weekend leeg. Dus niet dit keer.",
            topic: "Ik houd mijn agenda leeg, en {x} valt daar ook onder." },
          { generic: "Dank je voor het vragen. Ik houd mijn dag vrij.",
            topic: "Dank je voor je bericht over {x}. Ik houd mijn dag vrij." },
          { generic: "Ik doe het niet. Bel me gerust, dan praten we.",
            topic: "Ik heb nagedacht over {x}. Ik doe het niet. Bel me gerust, dan praten we." },
        ],
        duidelijk: [
          { generic: "Ik kom zondag niet langs. Ik hoef daar geen uitleg bij te geven, en het antwoord blijft hetzelfde.",
            topic: "Over {x}: nee. Ik hoef daar geen uitleg bij te geven, en het antwoord blijft hetzelfde." },
          { generic: "Ik hou van jullie én ik zeg nee. Die twee kunnen naast elkaar bestaan.",
            topic: "Ik heb nagedacht over {x}. Ik hou van jullie én ik zeg nee; die twee kunnen naast elkaar bestaan." },
          { generic: "Dit doe ik niet. Ik bewaak mijn energie en dat is mijn verantwoordelijkheid, niet die van jullie.",
            topic: "Wat betreft {x}: dat doe ik niet. Ik bewaak mijn energie en dat is mijn verantwoordelijkheid, niet die van jullie." },
          { generic: "Mijn antwoord is nee, ook als het vaker gevraagd wordt. Dat is geen afwijzing van jullie.",
            topic: "Je vroeg me over {x}. Mijn antwoord is nee, ook als het vaker gevraagd wordt. Dat is geen afwijzing van jullie." },
          { generic: "Ik houd mijn weekenden voorlopig vrij. Dat is geen afstand, maar een keuze voor mezelf.",
            topic: "Even over {x}: ik houd mijn agenda voorlopig leeg. Dat is geen afstand, maar een keuze voor mezelf." },
          { generic: "Deze keer kies ik voor mezelf en dat hoeft niemand goed te keuren. Een andere keer ben ik er graag weer bij.",
            topic: "Dank je voor je bericht over {x}. Deze keer kies ik voor mezelf en dat hoeft niemand goed te keuren. Een andere keer ben ik er graag weer bij." },
        ],
      },
      afspraak: {
        warm: [
          { generic: "Ik wil onze afspraak verzetten. Ik heb nu rust nodig. Ik stuur je snel een paar nieuwe momenten.",
            topic: "Over {x}: ik heb nu rust nodig, dus ik schuif het door. Ik stuur je snel een paar nieuwe momenten." },
          { generic: "Dank je voor je geduld. Onze afspraak laat ik voor nu even open; ik neem zelf contact op voor een nieuw moment.",
            topic: "Dank je voor je bericht over {x}. Ik laat het voor nu even open; ik neem zelf contact op voor een nieuw moment." },
          { generic: "Zullen we het verplaatsen naar volgende week? Deze week houd ik voor mezelf. Ik hoor graag wat jou past.",
            topic: "Wat betreft {x}: zullen we het verplaatsen naar volgende week? Deze week houd ik voor mezelf. Ik hoor graag wat jou past." },
          { generic: "Ik heb erover nagedacht en ik plan het liever later opnieuw. Nu is mijn energie beperkt. Ik kom er zelf op terug.",
            topic: "Ik heb nagedacht over {x}. Ik plan het liever later opnieuw; nu is mijn energie beperkt. Ik kom er zelf op terug." },
          { generic: "Ik merk dat ik meer ruimte nodig heb dan ik dacht, dus ik zeg onze afspraak af. Ik laat je weten wanneer het wel kan.",
            topic: "Ik merk dat ik meer ruimte nodig heb dan ik dacht. Even over {x}: dat wordt een andere keer. Ik laat je weten wanneer het wel kan." },
          { generic: "Ik houd onze afspraak graag korter. Een half uur is voor mij nu genoeg. Fijn dat je daarin meedenkt.",
            topic: "Je vroeg me over {x}. Ik houd het graag korter; een half uur is voor mij nu genoeg. Fijn dat je daarin meedenkt." },
        ],
        kort: [
          { generic: "Ik verzet onze afspraak. Ik stuur je nieuwe opties.",
            topic: "Over {x}: ik verzet het. Ik stuur je nieuwe opties." },
          { generic: "Ik zeg af. Ik neem zelf weer contact op.",
            topic: "Even over {x}: ik zeg af. Ik neem zelf weer contact op." },
          { generic: "Dit moment lukt niet. Volgende week?",
            topic: "Wat betreft {x}: dat lukt nu niet. Volgende week?" },
          { generic: "Ik houd het kort vandaag. Een half uur is genoeg.",
            topic: "Ik heb nagedacht over {x}: ik houd het kort. Een half uur is genoeg." },
          { generic: "Ik plan het later opnieuw. Ik kom er zelf op terug.",
            topic: "Je vroeg me over {x}. Ik plan het later opnieuw en kom er zelf op terug." },
          { generic: "Nu even niet. Ik houd mijn agenda leeg.",
            topic: "Dank je voor je bericht over {x}. Nu even niet; ik houd mijn agenda leeg." },
        ],
        duidelijk: [
          { generic: "Onze afspraak gaat niet door. Ik hoef daar geen reden voor te geven. Ik laat weten wanneer ik weer kan.",
            topic: "Over {x}: dat gaat niet door. Ik hoef daar geen reden voor te geven. Ik laat weten wanneer ik weer kan." },
          { generic: "Ik verplaats onze afspraak naar een later moment. Dat staat vast, en ik kom zelf met een nieuw voorstel.",
            topic: "Wat betreft {x}: ik verplaats het naar een later moment. Dat staat vast, en ik kom zelf met een nieuw voorstel." },
          { generic: "Ik zeg af. Als het nog eens gevraagd wordt, blijft mijn antwoord hetzelfde.",
            topic: "Even over {x}: ik zeg af. Als het nog eens gevraagd wordt, blijft mijn antwoord hetzelfde." },
          { generic: "Ik houd de afspraak korter dan gepland. Een half uur is de grens die ik nu stel.",
            topic: "Ik heb nagedacht over {x}. Ik houd het korter dan gepland; een half uur is de grens die ik nu stel." },
          { generic: "Nee, dit moment past niet. Ik plan zelf later opnieuw, daar hoef jij niets voor te doen.",
            topic: "Je vroeg me over {x}. Nee, dit moment past niet. Ik plan zelf later opnieuw, daar hoef jij niets voor te doen." },
          { generic: "Ik houd mijn agenda leeg en deze afspraak valt daar ook onder. Dat is een keuze, geen twijfel.",
            topic: "Ik houd mijn agenda leeg, en {x} valt daar ook onder. Dat is een keuze, geen twijfel." },
        ],
      },
    },
  },
  en: {
    examples: {
      werk: ["taking an extra shift", "covering a colleague's task", "working late on Friday", "joining another meeting", "delivering something before the weekend", "taking on an extra project"],
      sociaal: ["skipping a dinner", "a party on Saturday", "a quick call tonight", "a visit this weekend", "a weekend away", "drinks after work"],
      familie: ["not coming over on Sunday", "helping with the move", "a family birthday", "babysitting the kids", "a sleepover", "a family visit on Saturday"],
      afspraak: ["moving an appointment", "cancelling Tuesday's appointment", "rescheduling for later", "shortening the appointment", "moving it to next week", "postponing tomorrow's meeting"],
    },
    phrases: {
      werk: {
        warm: [
          { generic: "Thanks for thinking of me. I'm going to sit this one out; my energy is going into my own workload right now.",
            topic: "Thanks for thinking of me for {x}. I'm going to sit this one out; my energy is going into my own workload right now." },
          { generic: "Good of you to ask. This isn't something I can take on right now, and I'm confident it'll come together without me.",
            topic: "Good of you to ask. As for {x}, it isn't something I can take on right now, and I'm confident it'll come together without me." },
          { generic: "I've given it some thought and the answer is no. My energy is limited at the moment. Another time, I'd be glad to help.",
            topic: "I've thought about {x} and the answer is no. My energy is limited at the moment. Another time, I'd be glad to help." },
          { generic: "I know things are busy. Even so, I'm going to decline; I'm keeping my calendar deliberately light for now.",
            topic: "I know things are busy. On {x}, though, I'm going to decline; I'm keeping my calendar deliberately light for now." },
          { generic: "I appreciate the trust. I'm still going to say no; the space I have is needed for what's already on my plate.",
            topic: "I appreciate the trust. About {x}: I'm still going to say no; the space I have is needed for what's already on my plate." },
          { generic: "My task list stays as it is for now. This isn't going on it, and I'd rather say so now than halfway through.",
            topic: "My task list stays as it is for now. You asked about {x}; that isn't going on it, and I'd rather say so now than halfway through." },
        ],
        kort: [
          { generic: "I'm not picking this up.",
            topic: "On {x}: I'm not picking that up." },
          { generic: "That doesn't fit my calendar right now.",
            topic: "As for {x}, that doesn't fit my calendar right now." },
          { generic: "This one is a no from me.",
            topic: "{x} is a no from me." },
          { generic: "I'm sticking with what I've already got on.",
            topic: "I've thought about {x}. I'm sticking with what I've already got on." },
          { generic: "Thanks for asking. The answer is no.",
            topic: "Thanks for asking about {x}. The answer is no." },
          { generic: "I'm at capacity. This isn't getting added.",
            topic: "I'm at capacity, so {x} isn't getting added." },
        ],
        duidelijk: [
          { generic: "My answer to this is no. That's the whole message, and I'm comfortable leaving it there.",
            topic: "My answer on {x} is no. That's the whole message, and I'm comfortable leaving it there." },
          { generic: "This is a no, and it will still be a no if you ask again later. I'm protecting my workload.",
            topic: "On {x}: it's a no, and it will still be a no if you ask again later. I'm protecting my workload." },
          { generic: "I'm keeping to the hours and tasks we agreed, and this falls outside them.",
            topic: "{x} falls outside the hours and tasks we agreed, and I'm keeping to those." },
          { generic: "I'm not going along with this. A no is enough on its own; it doesn't need backing up.",
            topic: "I've thought about {x} and I'm not going along with it. A no is enough on its own; it doesn't need backing up." },
          { generic: "No. I'm holding my line on this, even if the timing is inconvenient.",
            topic: "About {x}: no. I'm holding my line on this, even if the timing is inconvenient." },
          { generic: "I'm saying no, and that stands without further justification. My availability is what it is at the moment.",
            topic: "Regarding {x}: I'm saying no, and that stands without further justification. My availability is what it is at the moment." },
        ],
      },
      sociaal: {
        warm: [
          { generic: "Lovely of you to ask. I'm going to give this one a miss; I need some rest and I'm letting myself have it.",
            topic: "Lovely of you to ask. About {x}: I'm going to give it a miss; I need some rest and I'm letting myself have it." },
          { generic: "I love that you want me there. Not this time though; I'm choosing rest. Next time, definitely.",
            topic: "I love that you thought of me. I've had a think about {x} and this time I'm choosing rest. Next time, definitely." },
          { generic: "It's a no from me. Not because I don't want to see you, but because I want nothing on for a while. Let's catch up when I've got more energy.",
            topic: "On {x}: it's a no from me. Not because I don't want to see you, but because I want nothing on for a while. Let's catch up when I've got more energy." },
          { generic: "Thanks for the invitation. I'm going to leave this one, and I hope you know that says nothing about you.",
            topic: "Thanks for your message about {x}. I'm going to leave this one, and I hope you know that says nothing about you." },
          { generic: "I can feel I need to keep things quiet right now, so I won't be joining. Thank you for asking; it means a lot.",
            topic: "I can feel I need to keep things quiet right now, and {x} is part of that. Thank you for asking; it means a lot." },
          { generic: "I'm a bit quieter than usual at the moment, and that's okay. Not this time, but I haven't forgotten you; I'll be in touch when I've got space again.",
            topic: "I'm a bit quieter than usual at the moment, and that's okay. You asked about {x}: not this time, but I haven't forgotten you. I'll be in touch when I've got space again." },
        ],
        kort: [
          { generic: "I'm skipping this one. Rest comes first right now.",
            topic: "About {x}: rest comes first right now." },
          { generic: "I'm going to bow out of this one. Kind of you to ask.",
            topic: "On {x}: I'm bowing out. Kind of you to ask." },
          { generic: "My energy is limited, so this one's a no.",
            topic: "As for {x}, my energy is limited, so that's a no." },
          { generic: "Not now, but you're on my mind.",
            topic: "You asked about {x}. Not now, but you're on my mind." },
          { generic: "Thanks for asking. I'll pass for now.",
            topic: "Thanks for asking about {x}. I'll pass for now." },
          { generic: "Not right now. I'll give you a shout when I'm up for things again.",
            topic: "I've thought about {x}. Not right now; I'll give you a shout when I'm up for things again." },
        ],
        duidelijk: [
          { generic: "This no is a choice for rest, not a judgement of you.",
            topic: "My no on {x} is a choice for rest, not a judgement of you." },
          { generic: "No, I won't be there. I'm leaving it at that, without a reason attached.",
            topic: "As for {x}: no. I'm leaving it at that, without a reason attached." },
          { generic: "I'm keeping my calendar clear for now, and this falls under that. It won't change if you ask again.",
            topic: "I'm keeping my calendar clear for now, and that includes {x}. It won't change if you ask again." },
          { generic: "I've thought this through properly and my answer is no. You can plan without me.",
            topic: "I've thought properly about {x} and my answer is no. You can plan without me." },
          { generic: "It's a no, and I'm not going to be talked round; I know what I need right now.",
            topic: "You asked about {x}. It's a no, and I'm not going to be talked round; I know what I need right now." },
          { generic: "Count me out this time. I'm saying it plainly so there's no maybe hanging in the air.",
            topic: "On {x}: count me out this time. I'm saying it plainly so there's no maybe hanging in the air." },
        ],
      },
      familie: {
        warm: [
          { generic: "This time I'm staying put; I need some rest, and I'm taking it. I love you all, and that doesn't change a thing.",
            topic: "On {x}: I need some rest, and I'm taking it. I love you all, and that doesn't change a thing." },
          { generic: "Sweet of you to ask. It's a no for now. Another time, when things are calmer, I'd love to.",
            topic: "Sweet of you to ask. I've thought about {x} and it's a no for now. Another time, when things are calmer, I'd love to." },
          { generic: "Glad you thought of me. This time I'm going to pass. That says nothing about how much you all mean to me.",
            topic: "Glad you thought of me. As for {x}, this time I'm going to pass. That says nothing about how much you all mean to me." },
          { generic: "I love you all, and I'm still saying no to this. My energy is limited and I'm choosing to look after it.",
            topic: "I love you all, and on {x} I'm still saying no. My energy is limited and I'm choosing to look after it." },
          { generic: "I appreciate you asking. This isn't right for me at the moment. I'll let you know when I have room again.",
            topic: "I appreciate you asking about {x}. It isn't right for me at the moment. I'll let you know when I have room again." },
          { generic: "I'm not coming this time, and I can just say that without anything being wrong. Hugs to everyone.",
            topic: "About {x}: not this time, and I can just say that without anything being wrong. Hugs to everyone." },
        ],
        kort: [
          { generic: "Not this time. I need some rest.",
            topic: "As for {x}, not this time. I need some rest." },
          { generic: "Love you, and it's a no. I'll ring you soon.",
            topic: "Love you, and it's a no on {x}. I'll ring you soon." },
          { generic: "No, and I say it with love.",
            topic: "About {x}: no, and I say it with love." },
          { generic: "My calendar stays clear for now, and this is no exception.",
            topic: "My calendar stays clear for now, and {x} is no exception." },
          { generic: "Thanks for thinking of me. I'm keeping my day free.",
            topic: "Thanks for thinking of me. On {x}, I'm keeping my day free." },
          { generic: "I'm going to say no, but ring me any time for a chat.",
            topic: "I've thought about {x}. I'm going to say no, but ring me any time for a chat." },
        ],
        duidelijk: [
          { generic: "This one's a no, and it doesn't need explaining. That's all there is to it.",
            topic: "On {x}: the answer is no, and it doesn't need explaining. That's all there is to it." },
          { generic: "I love you all and I'm saying no. Both of those can be true at once.",
            topic: "I've thought about {x}. I love you all and I'm saying no; both of those can be true at once." },
          { generic: "I'm not doing this one. Looking after my energy is my job, and I take it seriously.",
            topic: "As for {x}: I'm not doing it. Looking after my energy is my job, and I take it seriously." },
          { generic: "However many times this comes up, my answer is no. That isn't a rejection of you.",
            topic: "However many times {x} comes up, my answer is no. That isn't a rejection of you." },
          { generic: "This is a no: my energy is limited and I'm spending it carefully. That isn't distance; it's a choice for myself.",
            topic: "When it comes to {x}, this is a no: my energy is limited and I'm spending it carefully. That isn't distance; it's a choice for myself." },
          { generic: "I'm choosing myself this time, and that's allowed. Another time I'll happily be there.",
            topic: "You asked about {x}. I'm choosing myself this time, and that's allowed. Another time I'll happily be there." },
        ],
      },
      afspraak: {
        warm: [
          { generic: "I need some rest right now, so I'm going to move our appointment. I'll send you a few new times soon.",
            topic: "About {x}: I need some rest right now, so I'm going to move it. I'll send you a few new times soon." },
          { generic: "Thanks for your patience. I'm leaving our appointment open for now; I'll get in touch when I'm ready to find a new time.",
            topic: "Thanks for your message about {x}. I'm leaving it open for now; I'll get in touch when I'm ready to find a new time." },
          { generic: "I'd like to move our appointment to next week; this week I'm keeping for myself. Let me know what suits you.",
            topic: "As for {x}, I'd like to move it to next week; this week I'm keeping for myself. Let me know what suits you." },
          { generic: "I've thought about it and I'd rather reschedule for later. My energy is limited at the moment. I'll come back to you when the time is right.",
            topic: "I've thought about {x}. I'd rather reschedule for later; my energy is limited at the moment. I'll come back to you when the time is right." },
          { generic: "I'm finding I need more space than I expected, so I'm cancelling our appointment. I'll let you know when I'm ready to rebook.",
            topic: "I'm finding I need more space than I expected. On {x}: that will have to be another time. I'll let you know when I'm ready to rebook." },
          { generic: "I'd like to keep our appointment shorter. Half an hour is enough for me right now. Thanks for working with me on that.",
            topic: "You asked about {x}. I'd like to keep it shorter; half an hour is enough for me right now. Thanks for working with me on that." },
        ],
        kort: [
          { generic: "I'm moving our appointment. New times to follow.",
            topic: "On {x}: I'm moving it. New times to follow." },
          { generic: "I'm cancelling, and I'll leave it there for now.",
            topic: "I've thought about {x}. I'm cancelling, and I'll leave it there for now." },
          { generic: "That time doesn't work for me. I'll suggest another.",
            topic: "As for {x}, that time doesn't work for me. I'll suggest another." },
          { generic: "I'm keeping it short today. Half an hour is enough.",
            topic: "For {x}, I'm keeping it short. Half an hour is enough." },
          { generic: "I'll rebook later and come back to you with a date.",
            topic: "I'll rebook later and come back to you with a date for {x}." },
          { generic: "Not right now. I'm choosing rest for a while.",
            topic: "Regarding {x}: not right now. I'm choosing rest for a while." },
        ],
        duidelijk: [
          { generic: "Our appointment is cancelled. I don't need to give a reason for that. I'll let you know when I'm available again.",
            topic: "Where {x} is concerned, I'm cancelling. I don't need to give a reason for that. I'll let you know when I'm available again." },
          { generic: "I'm moving our appointment to a later date. That's settled, and I'll come to you with a new suggestion.",
            topic: "The date for {x} is being pushed back. That's settled, and I'll come to you with a new suggestion." },
          { generic: "I'm not rebooking for now. If it comes up again, my answer stays the same.",
            topic: "About {x}: I'm not rebooking for now. If it comes up again, my answer stays the same." },
          { generic: "I'm keeping the appointment shorter than planned. Half an hour is the limit I'm setting right now.",
            topic: "When it comes to {x}, I'm keeping it shorter than planned; half an hour is the limit I'm setting right now." },
          { generic: "I'm not fitting this in right now, and that's firm. I'll rebook when I have space.",
            topic: "You asked about {x}. I'm not fitting it in right now, and that's firm. I'll rebook when I have space." },
          { generic: "I've cleared my calendar for a while, and this appointment falls under that. It's a decision, not a doubt.",
            topic: "I've cleared my calendar for a while, and that covers {x}. It's a decision, not a doubt." },
        ],
      },
    },
  },
};
